[package]
name = "shallot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shallot-dedup = { path = "../shallot-dedup" }
anyhow = "1.0.75"
